### ISSUE TITLE
Conv1D doesn't work as expectation.

### ISSUE THREAD

**Issue by whbjzzwjxq** [socathie/circomlib-ml#2]
Source code location:
https://github.com/socathie/circomlib-ml/blob/master/circuits/Conv1D.circom

According to your test case: `Conv1D(20, 3, 2, 4, 3)`, it seems `in[19][*]` are never used, according to the definition of Conv, I think it is an unexpected behavior.

**Comment by whbjzzwjxq** [comment]
Here, `strides=3` ?

**Comment by socathie** [comment]
@whbjzzwjxq I am saying that depending on the choice of `strides` and the overall length, the last element(s) may or may not be convolved.

**Comment by whbjzzwjxq** [comment]
@socathie I see. So in that case, we could provide an optional pad?

**Comment by socathie** [comment]
@whbjzzwjxq Adding padding would be a code-breaking change, but I'm open to adding it in if there is huge demand. The only thing though is we usually want to keep these circuits more by reducing dimensions at each layer.
