### ISSUE TITLE
Floating number supports

### ISSUE THREAD

**Issue by LBruyne** [socathie/circomlib-ml#4]
Do these circuits supports floating numbers, or if i meets a floating number when calculating (such as dividing)? how should i deal with this problem

**Comment by socathie** [comment]
Hi, thanks for your interest in this ML library for the Circom language. Circom itself doesn't support floating point numbers, as this is still an active research area in ZKP. Division is also not ZKP compatible by default, and the currently the solutions are to either do an inverse multiplication or a lookup table.

However, I have built a Python library for automatically performing the conversion from floating point numbers to integer for Tensorflow Keras models. You can check it out here: [keras2circom](https://github.com/socathie/keras2circom)

**Comment by socathie** [comment]
These operations are not efficient in Circom, as Circom doesn't support non-quadratic operations. You can do so in other ZK circuit languages using lookup tables.
