### ISSUE TITLE
Understanding Applications

### ISSUE THREAD

**Issue by mangoplane** [socathie/circomlib-ml#6]
Hi,

I'm curious what sort of applications this allows, and how it might be used in practice. I'm rather new to ZKP, and only understand the basics. I could be wrong, but it seems like you can verify that the output of a network (public statement) was computed for some unknown input and training data (witness) with a publically known ML model (public circuit). Is that right? Also what are some example applications.

I'm also new to Circom.

**Comment by socathie** [comment]
Not sure if there is any TLDR way of explaining other than maybe referring to a playlist here with most of my talks on the topic: https://youtube.com/playlist?list=PL3C_huBgySWsdOs5QN5qa5LyWQb4Y1I3I&si=o5tGTBO406sjpGIa
