### ISSUE TITLE
Lack of PReLU

### ISSUE THREAD

**Issue by LehaoLin** [socathie/circomlib-ml#8]
Lack of PReLU.circom
reference from pytorch: https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html

**Comment by socathie** [comment]
Would you like to contribute by creating PReLU circuit?

**Comment by LehaoLin** [comment]
#9 pass the test. But maybe the logic is not correct. Please check.

**Comment by socathie** [comment]
I see. Actually since zkML currently concerns inference only and not training, PReLU is exactly the same as LeakyReLU? In this case, if having a template named PReLU is a must, I think it will be best for it to include LeakyReLU as a template to avoid duplicate code maintenance in the future.
